name: Symfony CI Pipeline

on:
  push:
    branches: [ ci, develop, main ]
  pull_request:
    branches: [ ci, develop, main ]

jobs:
  symfony-ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_pgsql
          tools: symfony, phpstan, phpunit

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: "${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}"
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Create missing sequences
        run: |
          psql -h localhost -U postgres -d ina_zaoui -c "CREATE SEQUENCE IF NOT EXISTS user_id_seq START 1 INCREMENT 1 OWNED BY \"user\".id;"
          psql -h localhost -U postgres -d ina_zaoui -c "SELECT setval('user_id_seq', (SELECT MAX(id) FROM \"user\"));"

      - name: Build
        env:
          APP_ENV: test
        run: |
          composer install
          php bin/console doctrine:database:drop --force --if-exists
          php bin/console doctrine:database:create
          php bin/console doctrine:migrations:migrate --no-interaction
          php bin/console doctrine:fixtures:load -n
      - name: Tests
        run: php bin/phpunit